### ISSUE TITLE
Link to Core team is wrong

### ISSUE THREAD

**Issue by tomasnorre** [jenkinsci/infra-cla#45]
Hi,

Then link in the readme to the core team is false.
https://github.com/orgs/jenkinsci/teams/core

Don't know where it should link to, so cannot create pull request, sorry.

**Comment by daniel-beck** [comment]
The link is correct; it's just not a publicly visible team.

**Comment by tomasnorre** [comment]
ok, Fair :)

**Comment by daniel-beck** [comment]
@tomasnorre Well, the process description is public because there's nothing secret about it, just references non-public things. I don't think you're the audience of this section.

That said, could probably rephrase to clarify, e.g.

> Add the person to the (not publicly visible) core team

**Comment by tomasnorre** [comment]
It's totally ok. I was just curious who was in the core team, and that's why I clicked the link.
